SELECT count(*) FROM hw2_1NF_invalidPKK1K2
SELECT count(*) FROM hw2_1NF_invalidPKK1K2
SELECT count(distinct(k1,k2)) FROM hw2_1NF_invalidPKK1K2
SELECT count(*) FROM hw2_1NF_invalidPKK1K2
SELECT k1,k2, a,count(*) FROM hw2_1NF_invalidPKK1K2 GROUP BY k1,k2,a HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_1NF_invalidPKK1K2 GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT count(*) FROM hw2_1nf_difficult
SELECT count(*) FROM hw2_1nf_difficult
SELECT count(distinct(k1,k2)) FROM hw2_1nf_difficult
SELECT count(*) FROM hw2_1nf_difficult
SELECT k1,k2, a,b,c,d,e,f,count(*) FROM hw2_1nf_difficult GROUP BY k1,k2,a,b,c,d,e,f HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_1nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_1nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT b)>1;
SELECT k1,COUNT(DISTINCT c) FROM hw2_1nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT c)>1;
SELECT k1,COUNT(DISTINCT d) FROM hw2_1nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT d)>1;
SELECT k1,COUNT(DISTINCT e) FROM hw2_1nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT e)>1;
SELECT k1,COUNT(DISTINCT f) FROM hw2_1nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT f)>1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_1nf_difficult GROUP BY k2 HAVING COUNT(DISTINCT a)>1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_1nf_difficult GROUP BY k2 HAVING COUNT(DISTINCT b)>1;
SELECT k2,COUNT(DISTINCT c) FROM hw2_1nf_difficult GROUP BY k2 HAVING COUNT(DISTINCT c)>1;
SELECT k2,COUNT(DISTINCT d) FROM hw2_1nf_difficult GROUP BY k2 HAVING COUNT(DISTINCT d)>1;
SELECT count(*) FROM hw2_2nf_not3nf
SELECT count(*) FROM hw2_2nf_not3nf
SELECT count(distinct(k)) FROM hw2_2nf_not3nf
SELECT count(*) FROM hw2_2nf_not3nf
SELECT k, a,b,c,count(*) FROM hw2_2nf_not3nf GROUP BY k,a,b,c HAVING COUNT(*)>1
SELECT COUNT(DISTINCT(a)) FROM hw2_2nf_not3nf HAVING COUNT(DISTINCT (a))>1;
SELECT COUNT(DISTINCT(b)) FROM hw2_2nf_not3nf HAVING COUNT(DISTINCT (b))>1;
SELECT COUNT(DISTINCT(c)) FROM hw2_2nf_not3nf HAVING COUNT(DISTINCT (c))>1;
SELECT COUNT(DISTINCT(k)) FROM hw2_2nf_not3nf HAVING COUNT(DISTINCT (k))>1;
SELECT a,COUNT(DISTINCT (b)) FROM hw2_2nf_not3nf GROUP BY a HAVING COUNT(DISTINCT (b))>1;
SELECT a,COUNT(DISTINCT (c)) FROM hw2_2nf_not3nf GROUP BY a HAVING COUNT(DISTINCT (c))>1;
SELECT b,COUNT(DISTINCT (a)) FROM hw2_2nf_not3nf GROUP BY b HAVING COUNT(DISTINCT (a))>1;
SELECT b,COUNT(DISTINCT (c)) FROM hw2_2nf_not3nf GROUP BY b HAVING COUNT(DISTINCT (c))>1;
SELECT count(*) FROM hw2_3nf_notbcnf
SELECT count(*) FROM hw2_3nf_notbcnf
SELECT count(distinct(k1,k2)) FROM hw2_3nf_notbcnf
SELECT count(*) FROM hw2_3nf_notbcnf
SELECT k1,k2, a,b,count(*) FROM hw2_3nf_notbcnf GROUP BY k1,k2,a,b HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf GROUP BY k1 HAVING COUNT(DISTINCT b)>1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf GROUP BY k2 HAVING COUNT(DISTINCT a)>1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf GROUP BY k2 HAVING COUNT(DISTINCT b)>1;
SELECT COUNT(DISTINCT(a)) FROM hw2_3nf_notbcnf HAVING COUNT(DISTINCT (a))>1;
SELECT COUNT(DISTINCT(b)) FROM hw2_3nf_notbcnf HAVING COUNT(DISTINCT (b))>1;
SELECT COUNT(DISTINCT(k1)) FROM hw2_3nf_notbcnf HAVING COUNT(DISTINCT (k1))>1;
SELECT COUNT(DISTINCT(k2)) FROM hw2_3nf_notbcnf HAVING COUNT(DISTINCT (k2))>1;
SELECT a,COUNT(DISTINCT (b)) FROM hw2_3nf_notbcnf GROUP BY a HAVING COUNT(DISTINCT (b))>1;
SELECT b,COUNT(DISTINCT (a)) FROM hw2_3nf_notbcnf GROUP BY b HAVING COUNT(DISTINCT (a))>1;
SELECT a,COUNT(DISTINCT (k2)) FROM hw2_3nf_notbcnf GROUP BY a HAVING COUNT(DISTINCT (k2))>1;
SELECT count(*) FROM hw2_3nf_notbcnf_2
SELECT count(*) FROM hw2_3nf_notbcnf_2
SELECT count(distinct(k1,k2)) FROM hw2_3nf_notbcnf_2
SELECT count(*) FROM hw2_3nf_notbcnf_2
SELECT k1,k2, a,b,count(*) FROM hw2_3nf_notbcnf_2 GROUP BY k1,k2,a,b HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf_2 GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf_2 GROUP BY k1 HAVING COUNT(DISTINCT b)>1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf_2 GROUP BY k2 HAVING COUNT(DISTINCT a)>1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf_2 GROUP BY k2 HAVING COUNT(DISTINCT b)>1;
SELECT COUNT(DISTINCT(a)) FROM hw2_3nf_notbcnf_2 HAVING COUNT(DISTINCT (a))>1;
SELECT COUNT(DISTINCT(b)) FROM hw2_3nf_notbcnf_2 HAVING COUNT(DISTINCT (b))>1;
SELECT COUNT(DISTINCT(k1)) FROM hw2_3nf_notbcnf_2 HAVING COUNT(DISTINCT (k1))>1;
SELECT COUNT(DISTINCT(k2)) FROM hw2_3nf_notbcnf_2 HAVING COUNT(DISTINCT (k2))>1;
SELECT a,COUNT(DISTINCT (b)) FROM hw2_3nf_notbcnf_2 GROUP BY a HAVING COUNT(DISTINCT (b))>1;
SELECT b,COUNT(DISTINCT (a)) FROM hw2_3nf_notbcnf_2 GROUP BY b HAVING COUNT(DISTINCT (a))>1;
SELECT a,COUNT(DISTINCT (k2)) FROM hw2_3nf_notbcnf_2 GROUP BY a HAVING COUNT(DISTINCT (k2))>1;
SELECT count(*) FROM hw2_bcnf
SELECT count(*) FROM hw2_bcnf
SELECT count(distinct(k1,k2)) FROM hw2_bcnf
SELECT count(*) FROM hw2_bcnf
SELECT k1,k2, a,b,count(*) FROM hw2_bcnf GROUP BY k1,k2,a,b HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_bcnf GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_bcnf GROUP BY k1 HAVING COUNT(DISTINCT b)>1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_bcnf GROUP BY k2 HAVING COUNT(DISTINCT a)>1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_bcnf GROUP BY k2 HAVING COUNT(DISTINCT b)>1;
SELECT COUNT(DISTINCT(a)) FROM hw2_bcnf HAVING COUNT(DISTINCT (a))>1;
SELECT COUNT(DISTINCT(b)) FROM hw2_bcnf HAVING COUNT(DISTINCT (b))>1;
SELECT COUNT(DISTINCT(k1)) FROM hw2_bcnf HAVING COUNT(DISTINCT (k1))>1;
SELECT COUNT(DISTINCT(k2)) FROM hw2_bcnf HAVING COUNT(DISTINCT (k2))>1;
SELECT a,COUNT(DISTINCT (b)) FROM hw2_bcnf GROUP BY a HAVING COUNT(DISTINCT (b))>1;
SELECT b,COUNT(DISTINCT (a)) FROM hw2_bcnf GROUP BY b HAVING COUNT(DISTINCT (a))>1;
SELECT a,COUNT(DISTINCT (k2)) FROM hw2_bcnf GROUP BY a HAVING COUNT(DISTINCT (k2))>1;
SELECT b,COUNT(DISTINCT (k1)) FROM hw2_bcnf GROUP BY b HAVING COUNT(DISTINCT (k1))>1;
SELECT count(*) FROM hw2_bcnf_2
SELECT count(*) FROM hw2_bcnf_2
SELECT count(distinct(id1,id2)) FROM hw2_bcnf_2
SELECT count(*) FROM hw2_bcnf_2
SELECT id1,id2, col1,col2,count(*) FROM hw2_bcnf_2 GROUP BY id1,id2,col1,col2 HAVING COUNT(*)>1
SELECT id1,COUNT(DISTINCT col1) FROM hw2_bcnf_2 GROUP BY id1 HAVING COUNT(DISTINCT col1)>1;
SELECT id1,COUNT(DISTINCT col2) FROM hw2_bcnf_2 GROUP BY id1 HAVING COUNT(DISTINCT col2)>1;
SELECT id2,COUNT(DISTINCT col1) FROM hw2_bcnf_2 GROUP BY id2 HAVING COUNT(DISTINCT col1)>1;
SELECT id2,COUNT(DISTINCT col2) FROM hw2_bcnf_2 GROUP BY id2 HAVING COUNT(DISTINCT col2)>1;
SELECT COUNT(DISTINCT(col1)) FROM hw2_bcnf_2 HAVING COUNT(DISTINCT (col1))>1;
SELECT COUNT(DISTINCT(col2)) FROM hw2_bcnf_2 HAVING COUNT(DISTINCT (col2))>1;
SELECT COUNT(DISTINCT(id1)) FROM hw2_bcnf_2 HAVING COUNT(DISTINCT (id1))>1;
SELECT COUNT(DISTINCT(id2)) FROM hw2_bcnf_2 HAVING COUNT(DISTINCT (id2))>1;
SELECT col1,COUNT(DISTINCT (col2)) FROM hw2_bcnf_2 GROUP BY col1 HAVING COUNT(DISTINCT (col2))>1;
SELECT col2,COUNT(DISTINCT (col1)) FROM hw2_bcnf_2 GROUP BY col2 HAVING COUNT(DISTINCT (col1))>1;
SELECT col1,COUNT(DISTINCT (id2)) FROM hw2_bcnf_2 GROUP BY col1 HAVING COUNT(DISTINCT (id2))>1;
SELECT col2,COUNT(DISTINCT (id1)) FROM hw2_bcnf_2 GROUP BY col2 HAVING COUNT(DISTINCT (id1))>1;
SELECT count(*) FROM hw2_compositepk
SELECT count(*) FROM hw2_compositepk
SELECT count(distinct(k1,k2)) FROM hw2_compositepk
SELECT count(*) FROM hw2_compositepk
SELECT k1,k2, c,count(*) FROM hw2_compositepk GROUP BY k1,k2,c HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT c) FROM hw2_compositepk GROUP BY k1 HAVING COUNT(DISTINCT c)>1;
SELECT k2,COUNT(DISTINCT c) FROM hw2_compositepk GROUP BY k2 HAVING COUNT(DISTINCT c)>1;
SELECT COUNT(DISTINCT(c)) FROM hw2_compositepk HAVING COUNT(DISTINCT (c))>1;
SELECT COUNT(DISTINCT(k1)) FROM hw2_compositepk HAVING COUNT(DISTINCT (k1))>1;
SELECT COUNT(DISTINCT(k2)) FROM hw2_compositepk HAVING COUNT(DISTINCT (k2))>1;
SELECT c,COUNT(DISTINCT (k2)) FROM hw2_compositepk GROUP BY c HAVING COUNT(DISTINCT (k2))>1;
SELECT count(*) FROM hw2_compositepk_2
SELECT count(*) FROM hw2_compositepk_2
SELECT count(distinct(k1,k2)) FROM hw2_compositepk_2
SELECT count(*) FROM hw2_compositepk_2
SELECT k1,k2, a,count(*) FROM hw2_compositepk_2 GROUP BY k1,k2,a HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_compositepk_2 GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_compositepk_2 GROUP BY k2 HAVING COUNT(DISTINCT a)>1;
SELECT COUNT(DISTINCT(a)) FROM hw2_compositepk_2 HAVING COUNT(DISTINCT (a))>1;
SELECT COUNT(DISTINCT(k1)) FROM hw2_compositepk_2 HAVING COUNT(DISTINCT (k1))>1;
SELECT COUNT(DISTINCT(k2)) FROM hw2_compositepk_2 HAVING COUNT(DISTINCT (k2))>1;
SELECT a,COUNT(DISTINCT (k2)) FROM hw2_compositepk_2 GROUP BY a HAVING COUNT(DISTINCT (k2))>1;
SELECT count(*) FROM hw2_easy
SELECT count(*) FROM hw2_easy
SELECT count(distinct(k)) FROM hw2_easy
SELECT count(*) FROM hw2_easy
SELECT k, b,count(*) FROM hw2_easy GROUP BY k,b HAVING COUNT(*)>1
SELECT count(*) FROM hw2_easy_strings
SELECT count(*) FROM hw2_easy_strings
SELECT count(distinct(k)) FROM hw2_easy_strings
SELECT count(*) FROM hw2_easy_strings
SELECT k, a,count(*) FROM hw2_easy_strings GROUP BY k,a HAVING COUNT(*)>1
SELECT COUNT(DISTINCT(a)) FROM hw2_easy_strings HAVING COUNT(DISTINCT (a))>1;
SELECT COUNT(DISTINCT(k)) FROM hw2_easy_strings HAVING COUNT(DISTINCT (k))>1;
SELECT count(*) FROM hw2_empty
SELECT count(*) FROM hw2_invalidPKk_not1NF
SELECT count(*) FROM hw2_invalidPKk_not1NF
SELECT count(distinct(k)) FROM hw2_invalidPKk_not1NF
SELECT count(*) FROM hw2_invalidPKk_not1NF
SELECT k, a,count(*) FROM hw2_invalidPKk_not1NF GROUP BY k,a HAVING COUNT(*)>1
SELECT count(*) FROM hw2_large_1
SELECT count(*) FROM hw2_large_1
SELECT count(distinct(id)) FROM hw2_large_1
SELECT count(*) FROM hw2_large_1
SELECT id, val1,val2,val3,val4,val5,count(*) FROM hw2_large_1 GROUP BY id,val1,val2,val3,val4,val5 HAVING COUNT(*)>1
SELECT COUNT(DISTINCT(val1)) FROM hw2_large_1 HAVING COUNT(DISTINCT (val1))>1;
SELECT COUNT(DISTINCT(val2)) FROM hw2_large_1 HAVING COUNT(DISTINCT (val2))>1;
SELECT COUNT(DISTINCT(val3)) FROM hw2_large_1 HAVING COUNT(DISTINCT (val3))>1;
SELECT COUNT(DISTINCT(val4)) FROM hw2_large_1 HAVING COUNT(DISTINCT (val4))>1;
SELECT COUNT(DISTINCT(val5)) FROM hw2_large_1 HAVING COUNT(DISTINCT (val5))>1;
SELECT COUNT(DISTINCT(id)) FROM hw2_large_1 HAVING COUNT(DISTINCT (id))>1;
SELECT val1,COUNT(DISTINCT (val2)) FROM hw2_large_1 GROUP BY val1 HAVING COUNT(DISTINCT (val2))>1;
SELECT val1,COUNT(DISTINCT (val3)) FROM hw2_large_1 GROUP BY val1 HAVING COUNT(DISTINCT (val3))>1;
SELECT val1,COUNT(DISTINCT (val4)) FROM hw2_large_1 GROUP BY val1 HAVING COUNT(DISTINCT (val4))>1;
SELECT count(*) FROM hw2_large_2
SELECT count(*) FROM hw2_large_2
SELECT count(distinct(k1,k2)) FROM hw2_large_2
SELECT count(*) FROM hw2_large_2
SELECT k1,k2, a,b,c,d,count(*) FROM hw2_large_2 GROUP BY k1,k2,a,b,c,d HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_large_2 GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_large_2 GROUP BY k1 HAVING COUNT(DISTINCT b)>1;
SELECT count(*) FROM hw2_large_3
SELECT count(*) FROM hw2_large_3
SELECT count(distinct(k1,k2)) FROM hw2_large_3
SELECT count(*) FROM hw2_large_3
SELECT k1,k2, a,b,c,d,e,f,g,h,l,m,count(*) FROM hw2_large_3 GROUP BY k1,k2,a,b,c,d,e,f,g,h,l,m HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_large_3 GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT count(*) FROM hw2_not2nf
SELECT count(*) FROM hw2_not2nf
SELECT count(distinct(k1,k2)) FROM hw2_not2nf
SELECT count(*) FROM hw2_not2nf
SELECT k1,k2, a,count(*) FROM hw2_not2nf GROUP BY k1,k2,a HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_not2nf GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT count(*) FROM hw2_not2nf_difficult
SELECT count(*) FROM hw2_not2nf_difficult
SELECT count(distinct(k1,k2)) FROM hw2_not2nf_difficult
SELECT count(*) FROM hw2_not2nf_difficult
SELECT k1,k2, a,b,count(*) FROM hw2_not2nf_difficult GROUP BY k1,k2,a,b HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_not2nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_not2nf_difficult GROUP BY k1 HAVING COUNT(DISTINCT b)>1;
SELECT count(*) FROM hw2_not2nf_easy
SELECT count(*) FROM hw2_not2nf_easy
SELECT count(distinct(k1,k2)) FROM hw2_not2nf_easy
SELECT count(*) FROM hw2_not2nf_easy
SELECT k1,k2, a,count(*) FROM hw2_not2nf_easy GROUP BY k1,k2,a HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_not2nf_easy GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT count(*) FROM hw2_onerow
SELECT count(*) FROM hw2_onerow
SELECT count(*) FROM hw2_pkbad_3
SELECT count(*) FROM hw2_pkbad_3
SELECT count(distinct(k)) FROM hw2_pkbad_3
SELECT count(*) FROM hw2_pkbad_3
SELECT k, a,count(*) FROM hw2_pkbad_3 GROUP BY k,a HAVING COUNT(*)>1
SELECT count(*) FROM hw2_pkbad_4
SELECT count(*) FROM hw2_pkbad_4
SELECT count(distinct(k1,k2)) FROM hw2_pkbad_4
SELECT count(*) FROM hw2_pkbad_4
SELECT k1,k2, a,count(*) FROM hw2_pkbad_4 GROUP BY k1,k2,a HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_pkbad_4 GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT count(*) FROM hw2_pkeasy
SELECT count(*) FROM hw2_pkeasy
SELECT count(distinct(k)) FROM hw2_pkeasy
SELECT count(*) FROM hw2_pkeasy
SELECT k, ab,count(*) FROM hw2_pkeasy GROUP BY k,ab HAVING COUNT(*)>1
SELECT COUNT(DISTINCT(ab)) FROM hw2_pkeasy HAVING COUNT(DISTINCT (ab))>1;
SELECT COUNT(DISTINCT(k)) FROM hw2_pkeasy HAVING COUNT(DISTINCT (k))>1;
SELECT count(*) FROM hw2_strings
SELECT count(*) FROM hw2_strings
SELECT count(distinct(k1,k2)) FROM hw2_strings
SELECT count(*) FROM hw2_strings
SELECT k1,k2, a,b,c,d,e,f,count(*) FROM hw2_strings GROUP BY k1,k2,a,b,c,d,e,f HAVING COUNT(*)>1
SELECT k1,COUNT(DISTINCT a) FROM hw2_strings GROUP BY k1 HAVING COUNT(DISTINCT a)>1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_strings GROUP BY k1 HAVING COUNT(DISTINCT b)>1;
SELECT k1,COUNT(DISTINCT c) FROM hw2_strings GROUP BY k1 HAVING COUNT(DISTINCT c)>1;
SELECT k1,COUNT(DISTINCT d) FROM hw2_strings GROUP BY k1 HAVING COUNT(DISTINCT d)>1;
SELECT k1,COUNT(DISTINCT e) FROM hw2_strings GROUP BY k1 HAVING COUNT(DISTINCT e)>1;
SELECT k1,COUNT(DISTINCT f) FROM hw2_strings GROUP BY k1 HAVING COUNT(DISTINCT f)>1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_strings GROUP BY k2 HAVING COUNT(DISTINCT a)>1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_strings GROUP BY k2 HAVING COUNT(DISTINCT b)>1;
SELECT k2,COUNT(DISTINCT c) FROM hw2_strings GROUP BY k2 HAVING COUNT(DISTINCT c)>1;
SELECT k2,COUNT(DISTINCT d) FROM hw2_strings GROUP BY k2 HAVING COUNT(DISTINCT d)>1;
